export const CONTACT_COUNTRY_CODE = "+91";
export const CONTACT_NUMBER = "9629674444";
export const CONTACT_DISPLAY_NUMBER = `${CONTACT_COUNTRY_CODE} 96296 74444`;
export const CONTACT_COUNTRY_CODE_DIGITS = CONTACT_COUNTRY_CODE.replace(
  "+",
  ""
);
export const CONTACT_NUMBER_WITH_COUNTRY = `${CONTACT_COUNTRY_CODE_DIGITS}${CONTACT_NUMBER}`;
export const CONTACT_TEL_LINK = `tel:${CONTACT_NUMBER}`;
export const CONTACT_TEL_LINK_WITH_COUNTRY = `tel:+${CONTACT_NUMBER_WITH_COUNTRY}`;
export const CONTACT_WHATSAPP_LINK = `https://wa.me/${CONTACT_NUMBER_WITH_COUNTRY}`;
